"""add equipment document upload fields

Revision ID: 3346962eca29
Revises: cd347587b5b4
Create Date: 2026-08-31 10:30:54.702733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3346962eca29'
down_revision: Union[str, Sequence[str], None] = 'cd347587b5b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('document_url', sa.String(length=500), nullable=True))
    op.add_column('equipment', sa.Column('document_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'document_filename')
    op.drop_column('equipment', 'document_url')
    # ### end Alembic commands ###
