"""add member login credentials and polymorphic refresh tokens

Revision ID: cd347587b5b4
Revises: 5311a4ba805e
Create Date: 2026-08-31 06:46:30.707453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd347587b5b4'
down_revision: Union[str, Sequence[str], None] = '5311a4ba805e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('refresh_tokens', sa.Column('member_id', sa.Integer(), nullable=True))
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_refresh_tokens_member_id'), 'refresh_tokens', ['member_id'], unique=False)
    op.create_foreign_key(None, 'refresh_tokens', 'members', ['member_id'], ['id'], ondelete='CASCADE')
    op.create_check_constraint('ck_refresh_tokens_exactly_one_owner', 'refresh_tokens', '(user_id IS NOT NULL AND member_id IS NULL) OR (user_id IS NULL AND member_id IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_refresh_tokens_exactly_one_owner', 'refresh_tokens', type_='check')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_refresh_tokens_member_id'), table_name='refresh_tokens')
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('refresh_tokens', 'member_id')
    op.drop_column('members', 'hashed_password')
    # ### end Alembic commands ###
